# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Jekyll Site Ci

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
    Ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Cache
              uses: actions/cache@v2
              with:
                  path: vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-

            - name: Set up Ruby
              # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
              # change this to (see https://github.com/ruby/setup-ruby#versioning):
              # uses: ruby/setup-ruby@v1
              uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
              with:
                  ruby-version: 2.6

            - name: Ruby Version
              run: |
                  ruby -v

            - name: Bundle Version
              run: |
                  bundle -v

            - name: Configure Bundle
              run: |
                  bundle config path vendor/bundle

            - name: bundle install
              run: |
                  bundle install --jobs 4 --retry 3

            - name: Run Jekyll Doctor
              run: |
                  bundle exec jekyll doctor

            - name: Run Jekyll Build
              run: |
                  bundle exec jekyll build --verbose --profile --trace

            - name: Run htmlproofer
              run: bundle exec htmlproofer ./_site --only-4xx --check-html --assume-extension --check-opengraph --check-favicon

            - name: Run Rspec Tests
              run: bundle exec rspec
